spring.application.name=Pharmacy_User_Service

server.port=9092

spring.datasource.url=jdbc:mysql://localhost:3306/pharmacy_app
spring.datasource.username=root
spring.datasource.password=Prash@320
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
